### ISSUE TITLE
Module '"react-hook-animate-number"' has no exported member 'useAnimateNumber'

### ISSUE THREAD

**Issue by untitledlt** [desduvauchelle/react-hook-animate-number#1]
Version: 1.0.0
Typescript: 4.6.2

Not sure what's going on here but TypeScript is complaining that:

> Module '"react-hook-animate-number"' has no exported member 'useAnimateNumber'. Did you mean to use 'import useAnimateNumber from "react-hook-animate-number"' instead?ts(2614)

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/7152884/164282720-64a9f013-a897-4152-b37d-956419f69128.png">

I solved it this way:
```
import UseAnimateNumber from 'react-hook-animate-number';
const { useAnimateNumber } = UseAnimateNumber;
```

**Comment by desduvauchelle** [comment]
Hi, 
Thanks for reaching out. 

I've updated the code so the usage is just 
```js
import useAnimateNumber from 'react-hook-animate-number'
```
(Please update the package and the instructions on the readme also have been updated). 

Let me know if you run into any other issue(s).
